# .rubocop.yml

inherit_mode:
  merge:
    - Exclude

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
  Exclude:
    - 'db/*/*'
    - 'bin/*'
    - 'node_modules/**/*'
Style/Documentation:
  Enabled: false
Metrics/ModuleLength:
  Enabled: false
Metrics/ClassLength:
  Max: 160
Metrics/BlockLength:
  Exclude:
    - "**/concerns/**/*.rb"
